// <auto-generated />
using CRUD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CRUD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171001082356_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("CRUD.Models.Glass", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("amount");

                    b.Property<string>("composition");

                    b.Property<long>("height");

                    b.Property<long>("invoice");

                    b.Property<long>("millim");

                    b.Property<string>("provider");

                    b.Property<long>("width");

                    b.HasKey("id");

                    b.ToTable("Glasses");
                });
#pragma warning restore 612, 618
        }
    }
}
